// ─── Tool catalog ────────────────────────────────────────────────────────────

export type ToolId =
  | "cursor"
  | "github_copilot"
  | "claude_consumer"
  | "claude_api"
  | "chatgpt_consumer"
  | "openai_api"
  | "gemini"
  | "windsurf";

export type UseCase = "coding" | "writing" | "data" | "research" | "mixed";

// ─── Per-tool entry (what the user fills in) ─────────────────────────────────

export interface ToolEntry {
  toolId: ToolId;
  plan: string;        // e.g. "Pro", "Business"
  seats: number;       // number of licences
  monthlySpend: number; // what they actually pay (USD, total not per-seat)
  enabled: boolean;    // toggle — some users won't use every tool
}

// ─── The full form state ──────────────────────────────────────────────────────

export interface AuditFormState {
  teamSize: number;
  useCase: UseCase;
  tools: ToolEntry[];
}

// ─── Audit result types (populated by audit engine — Feature 2) ───────────────

export type RecommendationType =
  | "downgrade"         // switch to cheaper plan same vendor
  | "switch_tool"       // switch to different vendor
  | "credits"           // buy via Credex credits
  | "optimal"           // already the best choice
  | "consolidate";      // paying for overlapping tools

export interface ToolAuditResult {
  toolId: ToolId;
  toolName: string;
  currentPlan: string;
  currentMonthlySpend: number;
  recommendationType: RecommendationType;
  recommendedPlan?: string;
  recommendedTool?: string;
  recommendedMonthlySpend: number;
  monthlySavings: number;
  annualSavings: number;
  reasoning: string;    // 1-sentence finance-grade explanation
  confidence: "high" | "medium" | "low";
}

export interface AuditSummary {
  totalCurrentSpend: number;
  totalRecommendedSpend: number;
  totalMonthlySavings: number;
  totalAnnualSavings: number;
  savingsPercentage: number;
  isAlreadyOptimal: boolean;
  hasHighSavings: boolean;       // >$500/mo → show Credex prominently
  toolResults: ToolAuditResult[];
  aiSummary?: string;             // generated by Anthropic API
  generatedAt: string;            // ISO timestamp
}

// ─── Shareable audit record (stored in DB, Feature 5 + 6) ─────────────────────

export interface AuditRecord {
  id: string;             // nanoid — public URL slug
  formState: AuditFormState;
  summary: AuditSummary;
  // PII stripped for public URL:
  publicFormState: Omit<AuditFormState, never>; // tools + useCase only, no email
  createdAt: string;
}

// ─── Lead capture (Feature 5) ─────────────────────────────────────────────────

export interface LeadCapture {
  email: string;
  companyName?: string;
  role?: string;
  teamSize?: number;
  auditId: string;
}

// ─── Plan catalog entries (used by audit engine) ──────────────────────────────

export interface PlanInfo {
  planId: string;
  planName: string;
  pricePerSeatPerMonth: number;  // USD
  minSeats?: number;
  maxSeats?: number;
  notes?: string;
  sourceUrl: string;
  verifiedDate: string;  // YYYY-MM-DD
}

export interface ToolCatalogEntry {
  id: ToolId;
  name: string;
  category: "coding" | "chat" | "api";
  plans: PlanInfo[];
  bestFor: UseCase[];
}
